#!/bin/bash
# Auto-Decision Engine installer (legacy / non-plugin path).
#
# Prefer the plugin install when possible:
#   /plugin marketplace add harshilmathur/autodecision
#   /plugin install autodecision@autodecision
#
# This script is for users who don't want plugins, or who want to vendor the
# skill files directly into a project's .claude/ directory.
#
# Source of truth: claude-plugin/. The .claude/ tree is generated by scripts/sync.sh
# and is what this installer copies from. Never edit .claude/ directly.
#
# Usage:
#   ./install.sh                          # Install to ~/.claude (global)
#   ./install.sh ~/.claude                # Same as above, explicit
#   ./install.sh ./your-project/.claude   # Install to a specific project

set -e

TARGET="${1:-$HOME/.claude}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Validate source exists. If .claude/ is missing, the user probably cloned a
# detached plugin bundle without running sync.sh first.
if [ ! -f "$SCRIPT_DIR/.claude/skills/autodecision/SKILL.md" ]; then
  echo "Error: .claude/skills/autodecision/SKILL.md not found." >&2
  echo "Run this script from the autodecision repo root." >&2
  echo "If you have claude-plugin/ but no .claude/, run ./scripts/sync.sh first." >&2
  exit 1
fi

# Create target directories if needed
mkdir -p "$TARGET/skills" "$TARGET/commands"

# Sync using rsync (idempotent, no nesting, removes stale files)
rsync -a --delete "$SCRIPT_DIR/.claude/skills/autodecision/" "$TARGET/skills/autodecision/"
rsync -a --delete "$SCRIPT_DIR/.claude/commands/autodecision/" "$TARGET/commands/autodecision/"

# Count files installed
SKILL_COUNT=$(find "$TARGET/skills/autodecision" -type f | wc -l | tr -d ' ')
CMD_COUNT=$(find "$TARGET/commands/autodecision" -type f | wc -l | tr -d ' ')

echo "Installed autodecision to $TARGET"
echo "  Skills: $SKILL_COUNT files"
echo "  Commands: $CMD_COUNT files"
echo ""
echo "Restart your Claude Code session to pick up the changes."
